import user from "../assets/images/user.png"
import sushi from "../assets/images/sushi.png"
import star from "../assets/images/star.png"
import basket from "../assets/images/basket.jpeg"
import search from "../assets/images/search.png"
import salad from "../assets/images/salad.png"
import rice_bowl from "../assets/images/rice_bowl.png"
import red_pin from "../assets/images/red_pin.png"
import pizza from "../assets/images/pizza.jpeg"
import pin from "../assets/images/pin.jpeg"
import noodle from "../assets/images/noodle.jpeg"
import nearly from "../assets/images/nearly.png"
import master_card from "../assets/images/master_card.png"
import location from "../assets/images/location.png"
import list from "../assets/images/list.png"
import like from "../assets/images/like.png"
import hotdog from "../assets/images/hotdog.png"
import hamburger from "../assets/images/hamburger.png"
import fries from "../assets/images/fries.png"
import fire from "../assets/images/fire.png"
import drink from "../assets/images/drink.png"
import donut from "../assets/images/donut.png"
import cutley from "../assets/images/cutley.png"
import car from "../assets/images/car.jpg"
import back from "../assets/images/back.png"


export default { user, sushi, star, basket, search, salad, rice_bowl, red_pin, pizza, pin, noodle, nearly, master_card, location, list, like, hotdog, hamburger, fries, fire, drink, donut, cutley, car, back }